[package]
name = "openarm_robot_initializer"
version = "0.1.0"
edition = "2024"

[dependencies]
peppygen = { path = ".peppy/libs/peppygen" }
peppylib = { path = ".peppy/libs/peppylib" }
tokio    = { version = "1", features = ["full"] }
tracing            = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
peppygen = { path = ".peppy/libs/peppygen", features = ["testing"] }
